# 1. \u6DFB\u52A0\u4F9D\u8D56
# 2. \u5F00\u653E\u8282\u70B9

management:
  endpoint:
    env:
      enabled: true
    shutdown:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'  # \u9ED8\u8BA4\u53EA\u5F00\u653E health, info \u8282\u70B9, "*"
